name: Build and Deploy

on:
  push:
    branches:
      - develop
      - 'feature-**'

jobs:
  run-build:
    runs-on: ubuntu-latest
    steps:
      - name: Get latest code
        uses: actions/checkout@v2

      - name: Install Node
        uses: actions/setup-node@v1
        with:
          node-version: '12.x'

      - name: Install dependencies
        run: npm ci

      - name: Build
        run: npm run build:prod:ghpages
        env:
          EMAIL_API_FROM: ${{ secrets.EMAIL_API_FROM }}
          EMAIL_API_KEY: ${{ secrets.EMAIL_API_KEY }}
          EMAIL_API_URL: ${{ secrets.EMAIL_API_URL }}

      - name: Upload build
        if: success()
        uses: actions/upload-artifact@v2
        with:
          name: www
          path: dist/site-pousada-muller

  run-deploy:
    runs-on: ubuntu-latest
    needs: run-build
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Download build
        uses: actions/download-artifact@v2
        with:
          name: www
          path: dist

      - name: Deploy to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@4.1.3
        with:
          BRANCH: gh-pages
          FOLDER: dist
        env:
          EMAIL_API_FROM: ${{ secrets.EMAIL_API_FROM }}
          EMAIL_API_KEY: ${{ secrets.EMAIL_API_KEY }}
          EMAIL_API_URL: ${{ secrets.EMAIL_API_URL }}
